name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          message="blabla"
          something="other"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.My_Secret }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/jolenzip/receiver/dispatches \
            -d "{\"event_type\": \"trigger-workflow\", \"client_payload\": {\"message\": \"$message\", \"something\": \"$something\", \"unit\": false, \"integration\": true}}"
