name: CI

on:
  workflow_dispatch:
    inputs:
      dispatch_type:
        description: 'how to trigger'
        required: true
        default: 'workflow_dispatch'
        type: choice
        options:
          - workflow_dispatch
          - repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow in another repo with inputs
        if: inputs.dispatch_type == 'workflow_dispatch'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: receiving_workflow
          repo: jonaslenz/receiver
          inputs: '{ "message": "blah blah", "something": false }'
          token: "${{ secrets.My_Secret }}"

      - name: Trigger Workflow in Another Repository
        if: inputs.dispatch_type == 'repository_dispatch'
        run: |
          message="blabla"
          something="other"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.My_Secret }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/jonaslenz/receiver/dispatches \
            -d "{\"event_type\": \"trigger-workflow\", \"client_payload\": {\"message\": \"$message\", \"something\": \"$something\", \"unit\": false, \"integration\": true}}"
